[feature-signup] 회원가입 Todos Epic 완료
wwh-techcamp-2018/team4-unnies pull request #42
Opened 2018-08-16 12:10 UTC by 1500sheep

## 회원가입 기능 구현 (#22)
- **daum 우편번호 api 사용** : iFrame 구조 적용
- **error Handling** : fieldName, message 형식으로 메시지 출력
- **signUp F/E B/E** : Domain, DTO, Service, RESTfulAPI
- **validation check** : F/E B/E 양방향 Validation 검사

2018-08-16 15:33 UTC, minsungryu requested changes
수고하셨습니다.

내일 데일리 미팅때 같이 얘기해봐요.

2018-08-16 15:33 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/domain/SignUpDTO.java
> +    @Pattern(regexp = Regex.EMAIL, message = "Invalid email")
MessageSourceAccessor를 등록했는데 굳이 필요할까요?

2018-08-16 15:33 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/domain/SignUpDTO.java
> +
사소하지만 불필요한 공백은 지워주세요 ㅎㅎ

2018-08-16 15:33 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/domain/User.java
> +public class User {
필드값에 `@Column`을 통해서 자세한 속성을 지정해주면 좋겠네요

2018-08-16 15:33 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/dto/SignUpDTO.java
> +
불필요한 공백도 제거하면 좋겠고, `matchPassword`와 `toEntity`는 중복 제거가 가능해 보이네요

그리고 동사로써 match의 사전적 의미를 보니 개인적으로는 `validatePassword`와 같은 이름이 더 나은 것 같아 추천해봅니다...

2018-08-16 15:33 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/exception/UnAuthenticationException.java
> +    // TODO : exception throw 시, field와 error message를 확인할 수 있는 방법은?!
field 속성이 모든 경우에 필요한 건 아니라고 봅니다.

API 통신간 예외와 일반 로직의 예외를 구분지어서 고민해봐야겠어요.

그리고 모든 예외 클래스에 속성을 넣는 것 보다는 상속을 활용해보면 좋겠습니다.

2018-08-16 15:33 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/security/ExceptionControllerAdvice.java
> +    @ResponseStatus(value = HttpStatus.BAD_REQUEST)
400이 말이 안되는 건 아닌데... NotFound면 404아닌가요? 고민되네요

2018-08-16 15:33 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/security/ExceptionControllerAdvice.java
> +    @ResponseStatus(value = HttpStatus.UNAUTHORIZED)
이건 400 아닌가요?

2018-08-16 15:33 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/service/UserService.java
> +
ㅠㅠ컨벤션을 맞춰주세요

2018-08-16 15:33 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/utils/Regex.java
> +public class Regex {
enum이 더 적합해보이네요.

그리고 그냥 Regex보다는 좀 더 의미있는 이름이면 좋겠어요

2018-08-16 15:33 UTC, minsungryu commented on src/main/resources/static/css/bootstrap-theme.css
> +/*!
min을 사용하세요

2018-08-16 15:33 UTC, minsungryu commented on src/main/resources/static/css/bootstrap-theme.css.map
> +{"version":3,"sources":["less/theme.less","less/mixins/vendor-prefixes.less","bootstrap-theme.css","less/mixins/gradients.less","less/mixins/reset-filter.less"],"names":[],"mappings":"AAcA;;;;;;EAME,
우리 프로젝트에는 불필요한 파일입니다. 모두 붙여넣기 하지 마시고 용도를 찾아본 후 하면 좋겠습니다.

2018-08-16 15:33 UTC, minsungryu commented on src/main/resources/static/js/address.js
> +const element_layer = document.getElementById('layer');
수업시간에 배운 querySelector 사용하는걸로 통일하면 어떨까요.

그리고 iframe 방식은 단점이 좀 있어서 최근에 사용하지 않는 추세입니다.

팝업도 별로지만 우리나라 정서상 거슬리는 정도는 아닐듯하네요.

modal 방식으로 가능하면 도전해보는것도...

2018-08-16 15:33 UTC, minsungryu commented on src/main/resources/static/js/npm.js
> +// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
오마이갓... 무분별한 복붙...

2018-08-16 15:33 UTC, minsungryu commented on src/main/resources/static/js/signup.js
> +    const email = `${$("#email").value}`;
address는 이해가 가지만 나머지 값들은 이렇게 표현할 필요가 없어 보이는데요

2018-08-16 15:33 UTC, minsungryu commented on src/main/resources/static/js/signup.js
> +        credentials:"same-origin",
문자열을 표현할 때 `'` `"` 둘 중 하나로 통일해서 사용하면 좋겠어요

2018-08-16 15:33 UTC, minsungryu commented on src/main/resources/static/js/signup.js
> +        body: JSON.stringify({
json 표현할 때 지금처럼 `key: value`가 좀 더 일반적인 방식입니다.

표현을 통일해서 해주시고 위에도 여기처럼 바꿔주세요!

2018-08-16 15:33 UTC, minsungryu commented on src/main/resources/static/js/signup.js
> +    .then(response=>{
`response => {`

2018-08-16 15:33 UTC, minsungryu commented on src/main/resources/static/js/signup.js
> +        alert("회원가입을 축하드립니다.");
bootstrap도 사용하니 alert대신 modal을 이용해보세요.

그런데 사실 축하해줄 필요가 없는듯요..ㅋㅋ

2018-08-16 15:33 UTC, minsungryu commented on src/main/resources/static/js/signup.js
> +        console.log(error);
불필요한 error 로그도 남기지 않는게 나아요

2018-08-16 15:33 UTC, minsungryu commented on src/main/resources/static/js/signup.js
> +    var regex_name = /[가-힣]{2,16}|[a-zA-Z]{2,16}/;
var?!

2018-08-16 15:33 UTC, minsungryu commented on src/main/resources/static/js/signup.js
> +    for(let key in registerFlag){
let보단 const가 적합해보여요

2018-08-16 15:33 UTC, minsungryu commented on src/main/resources/static/signup.html
> +    <title>강석윤 머싱썽</title>
ㅇㅋ...

2018-08-16 15:33 UTC, minsungryu commented on src/main/resources/static/signup.html
> +<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
무분별한 복붙은 지양하세요
static 폴더에 다운받아서 연결했으니 필요하지 않습니다

2018-08-16 15:33 UTC, minsungryu commented on src/main/resources/static/signup.html
> +                        <strong style="color:red; visibility:hidden;">invalid email</strong>
예제를 복붙해서 그렇겠지만 js도 그렇고 next, prev는 구조가 바뀌면 다시 수정해야하는 작업이 많을거에요.(크롱 조언)
selector를 통해서 의미있는 코드를 만들어야겠네요

2018-08-16 15:33 UTC, minsungryu commented on src/test/java/com/baemin/nanumchan/domain/UserValidationTest.java
> +}
테스트를 꼼꼼하게 잘 해주셨네요 👍

2018-08-16 15:33 UTC, minsungryu commented on src/test/java/com/baemin/nanumchan/web/ApiUserAcceptanceTest.java
> +        ResponseEntity<RestResponse> response = template.postForEntity("/api/users", signUpDTO, RestResponse.class);
중복제거 가능해보여요

2018-08-16 15:36 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/dto/SignUpDTO.java
> +
그리고 같은 파일이 두 개네요

2018-08-17 06:41 UTC, hyukjin-lee commented on src/main/java/com/baemin/nanumchan/domain/SignUpDTO.java
> +    @Pattern(regexp = Regex.EMAIL, message = "Invalid email")
Mission complete

2018-08-17 06:42 UTC, hyukjin-lee commented on src/main/java/com/baemin/nanumchan/domain/SignUpDTO.java
> +
mission complete

2018-08-17 06:44 UTC, hyukjin-lee commented on src/main/java/com/baemin/nanumchan/domain/User.java
> +public class User {
mission complete

2018-08-17 06:54 UTC, 1500sheep commented on src/main/java/com/baemin/nanumchan/dto/SignUpDTO.java
> +
```java
private boolean matchPassword() {
        return password.equals(confirmPassword);
    }

    public User toEntity(PasswordEncoder passwordEncoder) throws UnAuthenticationException {
        if (!matchPassword()) {
            throw UnAuthenticationException.invalidPassword();
        }

        return User.builder()
                .name(name)
                .password(passwordEncoder.encode(password))
                .email(email)
                .phoneNumber(phoneNumber)
                .address(address)
                .build();
    }
```
matchPassword를 signUpDTO에서만 확인하게 변경하였습니다.

2018-08-17 10:12 UTC, hyukjin-lee commented on src/main/java/com/baemin/nanumchan/dto/SignUpDTO.java
> +
validate는 저희가 정한 규칙에 어긋났을 때 사용하는 단어라고 생각합니다. 지금 confirmpassword와 password를 match 시켜서 확인하는 것이므로 match가 맞다고 생각하였습니다.

2018-08-17 10:17 UTC, hyukjin-lee commented on src/main/java/com/baemin/nanumchan/security/ExceptionControllerAdvice.java
> +    @ResponseStatus(value = HttpStatus.BAD_REQUEST)
not found니까 404가 맞는 것 같습니다! 리뷰 반영했습니다

2018-08-17 10:20 UTC, hyukjin-lee commented on src/main/java/com/baemin/nanumchan/security/ExceptionControllerAdvice.java
> +    @ResponseStatus(value = HttpStatus.UNAUTHORIZED)
수정했습니다

2018-08-17 10:21 UTC, hyukjin-lee commented on src/main/java/com/baemin/nanumchan/service/UserService.java
> +
수정 완료 했습니다

2018-08-17 10:31 UTC, hyukjin-lee commented on src/main/java/com/baemin/nanumchan/utils/Regex.java
> +public class Regex {
enum은 정확히 잘 모르겠어서 이름만 일단 바꾸겠습니다

2018-08-17 10:32 UTC, hyukjin-lee commented on src/main/resources/static/css/bootstrap-theme.css
> +/*!
지웠습니다~

2018-08-17 10:32 UTC, hyukjin-lee commented on src/main/resources/static/css/bootstrap-theme.css.map
> +{"version":3,"sources":["less/theme.less","less/mixins/vendor-prefixes.less","bootstrap-theme.css","less/mixins/gradients.less","less/mixins/reset-filter.less"],"names":[],"mappings":"AAcA;;;;;;EAME,
지웠습니다!

2018-08-17 10:36 UTC, hyukjin-lee commented on src/main/resources/static/js/address.js
> +const element_layer = document.getElementById('layer');
팝업으로 교체했습니다. querySelector로 모두 교체했습니다.

2018-08-17 10:47 UTC, hyukjin-lee commented on src/main/resources/static/js/npm.js
> +// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
지웠습니다 ~~

2018-08-17 10:52 UTC, hyukjin-lee commented on src/main/resources/static/js/signup.js
> +        credentials:"same-origin",
넵 명심하겠습니다

2018-08-17 10:53 UTC, hyukjin-lee commented on src/main/resources/static/js/signup.js
> +    const email = `${$("#email").value}`;
네 실수했습니다 ㅠㅠ

2018-08-17 10:57 UTC, hyukjin-lee commented on src/main/resources/static/js/signup.js
> +    .then(response=>{
꼼꼼하시네유 ㅎㅎ

2018-08-17 10:57 UTC, hyukjin-lee commented on src/main/resources/static/js/signup.js
> +        console.log(error);
지웠습니다~

2018-08-17 10:57 UTC, hyukjin-lee commented on src/main/resources/static/js/signup.js
> +    for(let key in registerFlag){
넵 바꿨습니다

2018-08-17 10:57 UTC, hyukjin-lee commented on src/main/resources/static/js/signup.js
> +    var regex_name = /[가-힣]{2,16}|[a-zA-Z]{2,16}/;
oh sorry...

2018-08-17 10:59 UTC, hyukjin-lee commented on src/main/resources/static/signup.html
> +    <title>강석윤 머싱썽</title>
ㅇㅋ...

2018-08-17 11:00 UTC, hyukjin-lee commented on src/main/resources/static/signup.html
> +<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
넵

2018-08-17 11:00 UTC, hyukjin-lee commented on src/test/java/com/baemin/nanumchan/domain/UserValidationTest.java
> +}
보고 배웠습니다

2018-08-17 11:35 UTC, merged