login 기능
wwh-techcamp-2018/team4-unnies pull request #43
Opened 2018-08-16 13:32 UTC by 1500sheep

## login 기능 (#30)

2018-08-16 15:47 UTC, minsungryu requested changes
#42 와 동일한 피드백

추가로, 필요없는 코드들이 보이는데 커밋 전에 꼼꼼히 확인해주세요.

stash 기능을 활용해보는 것도 좋은데 잘 안되면 gui 툴 등으로 익숙해지고 cli를 사용해보는 것도 좋을 것 같네요

2018-08-16 15:47 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/dto/LoginDTO.java
> +    @Pattern(regexp = Regex.EMAIL, message = "Invalid email")
이전 PR과 마찬가지로 messages.properties를 활용해보면 좋겠습니다.

2018-08-16 15:47 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/service/UserService.java
> +        if(!passwordEncoder.matches(loginDTO.getPassword(),maybeUser.getPassword())){
저도 이거 고민이 많이 되는데요

`get`으로 꺼내와서 비교하는 것보다

도메인 객체에 일을 시키는 편이 아무래도 객체지향적인 측면에서 더 나아보입니다.

2018-08-16 15:47 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/utils/SessionUtils.java
> +    public static void setUserInSession(HttpSession session, User loginUser) {
User 정보 전체를 저장하기로 결정하신건가요?

2018-08-17 11:07 UTC, hyukjin-lee commented on src/main/java/com/baemin/nanumchan/dto/LoginDTO.java
> +    @Pattern(regexp = Regex.EMAIL, message = "Invalid email")
적용했습니다!

2018-08-17 12:21 UTC, hyukjin-lee commented on src/main/java/com/baemin/nanumchan/service/UserService.java
> +        if(!passwordEncoder.matches(loginDTO.getPassword(),maybeUser.getPassword())){
수정했습니다!

2018-08-18 05:46 UTC, merged