상세페이지 todo
wwh-techcamp-2018/team4-unnies pull request #90
Opened 2018-08-22 12:45 UTC by 1500sheep

완전히 구현하진 않은 상태입니다(페이지네이션, login.html , sign.html 깨집니다.)
제 코드 부분이 필요해서 pull request 하고 추가적으로 push 하도록 하겠슴다

2018-08-22 15:42 UTC, minsungryu requested changes
정말 힘들었을텐데 두 분 모두 수고많으셨네요! 전반적으로 구현 잘 하신 것 같아요. 매우 든든합니다ㅎㅎ

몇 가지 피드백 남겼으니 참고해보세요~

2018-08-22 15:42 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/domain/OrderRepository.java
> +    Optional<Long> countByProduct(Product product);
Optional인 이유가 있을까요? 무조건 숫자가 나올 것 같은데

2018-08-22 15:42 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/domain/Review.java
> +    public String toString() {
lombok을 사용하니 `@ToString` 해도 될듯요

2018-08-22 15:42 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/domain/Status.java
> +public enum Status {
OrderStatus와 같이 이름이 명시적이면 좋겠어요

상태는 ON_PARTICIPATING, ON_SHARING, COMPLETE_SHARING 세 가지 말고는 어떤 의미인지 내일 설명해주세요

2018-08-22 15:42 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/dto/ProductDTO.java
> +    public Product toEntity(Category category, List<ProductImage> productImages, Location location, User user) {
파라미터가 많으면 좋지 않은 것 같은데 다른 방법이 없을까요?ㅠㅠ 같이 고민해봐요

2018-08-22 15:42 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/security/BasicAuthInterceptor.java
> +                    LoginDTO.builder().email(values[0]).password(values[1]).build()
이정도는 굳이 빌더를 사용하지 않아도 될 것 같아요

2018-08-22 15:42 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/service/ProductService.java
> +        Integer orderCount = (int) (long) orderRepository.countByProduct(product).orElse(NO_ONE);
`(int) (long)` ?!?!

2018-08-22 15:42 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/domain/ReviewRepository.java
> +    Double getAvgRatingByWriterId(Long writerId);
아래 코드 보니까 Optional이 나을듯요

2018-08-22 15:42 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/service/ProductService.java
> +        if (ownerRating == null) {
Repository에서 Optional을 반환해줄 수 있다면

`Double ownerRating = reviewRepository.getAvgRatingByWriterId(product.getOwner().getId()).orElse(0);` 이런 형태도 가능할듯요.

`getAvgRatingByWriterId(product.getOwner().getId())` 이 부분에 바로 User를 넣어줄 수는 없을까요?

2018-08-22 15:42 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/service/ProductService.java
> +    public Order order(Long productId, OrderDTO orderDTO, User user) {
OrderDTO가 있음에도 Product와 User 정보를 받는다는 것은 OrderDTO가 제 역할을 못하고 있는 것 같아요

2018-08-22 15:42 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/service/ProductService.java
> +    public Review uploadReview(User user, Long productId, ReviewDTO reviewDTO) {
ReviewDTO도 마찬가지라고 생각합니다

2018-08-22 15:42 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/support/domain/AbstractEntity.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
제 실수... 감사합니다 😅

2018-08-22 15:42 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/web/ApiProductController.java
> +    @PostMapping("/{id}/order")
orders

2018-08-22 15:42 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/web/ApiProductController.java
> +    @PostMapping("/{id}/review")
reviews

2018-08-22 15:42 UTC, minsungryu commented on src/main/resources/static/css/detail.css
> +#user-profile #user-profile-image {
id 사용이 과한데 같이 다른 방법을 고민해봐요

2018-08-22 15:42 UTC, minsungryu commented on src/main/resources/static/js/ReviewList.js
> +                    return response.json();
`!response.ok`일 때 throw해서 catch로 보내는건 어떨까요

2018-08-22 15:42 UTC, minsungryu commented on src/main/resources/static/js/ReviewList.js
> +                $('#product-comments-list').innerHTML = data.map(review => reviewTemplate(review)).join('');
이런 경우는 `data.map(reviewTemplate).join('')`으로 줄일 수 있어요

2018-08-22 15:42 UTC, minsungryu commented on src/main/resources/static/js/detail.js
> +    let deliveryType = $('#radio-riders').value === '배민라이더스' ? 'BAEMIN_RIDER' : 'PICKUP';
const

2018-08-22 15:42 UTC, minsungryu commented on src/main/resources/static/js/detail.js
> +    fetch(`/api/products/${productId}/order`, {
orders

2018-08-22 15:42 UTC, minsungryu commented on src/main/resources/static/js/detail.js
> +            if(response.status >= 400 && response.status <= 404){
400는 잘못된 요청 / 404는 서버에서 처리할 end point가 없다는 뜻인데 권한이 없다고 알려주는 것은 의미가 잘못된 것 같아요.

그리고 alert는 고쳐주세요. 곳곳의 console.log도...

2018-08-22 15:42 UTC, minsungryu commented on src/main/resources/static/js/detail.js
> +            if(response.status >= 400 && response.status <= 404){
그리고 x00대 코드가 비슷한 유형의 응답을 하는 것은 맞지만

뭉뚱그려서 처리할거면 status/100을 해서 비교해도 될듯요

2018-08-22 15:42 UTC, minsungryu commented on src/main/resources/static/js/modal.js
> +export function openModal(event){
e? event? 통일해주세요~ 투표 고고?

2018-08-22 15:42 UTC, minsungryu commented on src/main/resources/static/js/modal.js
> +    const selectedStars = $('#product1').getElementsByClassName('star');
`$all('#product1 .star')`는 어떤가요?

2018-08-22 15:42 UTC, minsungryu commented on src/main/resources/static/js/modal.js
> +    for (let selectedStar of selectedStars) {
const

2018-08-22 15:42 UTC, minsungryu commented on src/main/resources/static/js/modal.js
> +        if(selectedStar.className.indexOf('selected') > -1){
`classList.contains`를 사용해보세요

2018-08-22 15:42 UTC, minsungryu commented on src/main/resources/static/js/modal.js
> +    const selectedStars = $('#product1').getElementsByClassName('star');
애초에 `$all('#product1 .star.selected')` 하면 되네..

2018-08-22 15:42 UTC, minsungryu commented on src/main/resources/static/js/rating.js
> +        if (!event.target.matches('.rating')) return;
matches는 처음보네요 굿 👍

2018-08-22 15:42 UTC, minsungryu commented on src/main/resources/static/js/signup.js
> +import { $, $all } from './lib/utils.js';
$all 안쓰는데 굳이 import 할 필요는 없어요

2018-08-22 15:42 UTC, minsungryu commented on src/main/resources/static/js/signup.js
바로 아래줄에 리뷰가 안달리네요

underscore 의존성 추가했으니 monitorRegisterButton을 어떻게 바꿀 수 있나 찾아보세요 :)

2018-08-22 15:42 UTC, minsungryu commented on src/test/java/com/baemin/nanumchan/domain/OrderTest.java
> +        order = Order.builder()
builder는 과한듯해요

2018-08-22 15:45 UTC, minsungryu commented on src/main/resources/static/js/template/DetailTemplate.js
> +        i < rating ? html += `<span class='fa fa-star checked'></span>`: html += `<span class='fa fa-star'></span>`;
굳이 이 코드를 개선하자면 `html += i < rating ?`<span class='fa fa-star checked'></span>`: `<span class='fa fa-star'></span>``가 될테고

그냥 `<span class='fa fa-star'>` 5개 만든다음에 0 ~ rating까지 `checked` 클래스를 추가해주면 될듯요

2018-08-23 01:42 UTC, Kelicia91 reviewed
수고하셨습니다~!
ps. 민성님이 리뷰를 꼼꼼하게 해주셔서 좋네요 :-)

2018-08-23 01:42 UTC, Kelicia91 commented on src/main/java/com/baemin/nanumchan/domain/Status.java
> +public enum Status {
네이밍 관련해서 동감합니다ㅎㅎ

2018-08-23 01:42 UTC, Kelicia91 commented on src/main/java/com/baemin/nanumchan/service/ProductService.java
> +        Integer orderCount = (int) (long) orderRepository.countByProduct(product).orElse(NO_ONE);
......?!

2018-08-23 01:42 UTC, Kelicia91 commented on src/main/resources/static/js/modal.js
> +export function openModal(event){
전.. 줄임말보다는 event 에 한표..ㅎ

2018-08-23 01:52 UTC, 1500sheep commented on src/main/java/com/baemin/nanumchan/domain/OrderRepository.java
> +    Optional<Long> countByProduct(Product product);
맞습니다. 무조건 숫자군요...;;

2018-08-23 01:52 UTC, 1500sheep commented on src/main/java/com/baemin/nanumchan/domain/Review.java
> +    public String toString() {
lombok 사용하게 되면 product랑 writer도 나오게 됩니다.

2018-08-23 01:55 UTC, 1500sheep commented on src/main/java/com/baemin/nanumchan/domain/Status.java
> +public enum Status {
```
//About Order
ON_SHARING,
COMPLETE_SHARING,

//About Product Detail Info
EXPIRED,
FULL_PARTICIPANTS,
ON_PARTICIPATING
```
order 때의 status와 product때 status가 다릅니다. 이 부분을 Status 한 곳에서 다루고 있는데  OrderStatus, ProductDetailStatus 이렇게 나누면 너무 쪼개는 것 같아서 하나로 뒀습니다.

2018-08-23 01:55 UTC, 1500sheep commented on src/main/java/com/baemin/nanumchan/security/BasicAuthInterceptor.java
> +                    LoginDTO.builder().email(values[0]).password(values[1]).build()
빌더에 중독스...ㅋㅋ

2018-08-23 01:56 UTC, 1500sheep commented on src/main/java/com/baemin/nanumchan/security/BasicAuthInterceptor.java
> +                    LoginDTO.builder().email(values[0]).password(values[1]).build()
아 `userService.login(LoginDTO loginDTO)` 입니다!

2018-08-23 01:58 UTC, 1500sheep commented on src/main/resources/static/js/modal.js
> +        if(selectedStar.className.indexOf('selected') > -1){
넵

2018-08-23 02:03 UTC, 1500sheep commented on src/main/resources/static/js/template/DetailTemplate.js
> +        i < rating ? html += `<span class='fa fa-star checked'></span>`: html += `<span class='fa fa-star'></span>`;
ratingTemplate은 메인페이지, 상세페이지, 마이페이지 등에서 쓰기 위해서 template으로 뺐습니다.

2018-08-23 02:16 UTC, 1500sheep commented on src/main/java/com/baemin/nanumchan/domain/ReviewRepository.java
> +    Double getAvgRatingByWriterId(Long writerId);
아 그렇네요 ㅋㅋㅋ 후...;;

2018-08-23 02:16 UTC, 1500sheep commented on src/main/java/com/baemin/nanumchan/service/ProductService.java
> +        Integer orderCount = (int) (long) orderRepository.countByProduct(product).orElse(NO_ONE);
ㅋㅋㅋㅋㅋㅋㅋ 혁진님 헬프 좀 ...ㅋㅋ(사실 stackoverflow에서 갖다 썼습니다.)

2018-08-23 02:16 UTC, 1500sheep commented on src/main/java/com/baemin/nanumchan/service/ProductService.java
> +    public Order order(Long productId, OrderDTO orderDTO, User user) {
OrderDTO는 프런트에서 오는 body 값만 받고 있습니다. controller에서 OrderDTO에 User와 product id를 넣어주라는 의미 인건가요?

2018-08-23 02:16 UTC, 1500sheep commented on src/main/java/com/baemin/nanumchan/service/ProductService.java
> +    public Order order(Long productId, OrderDTO orderDTO, User user) {
현재 결제 페이지를 만들지 않아서 상세페이지에서 나눔 신청할 때 보낼 수 있는 유일한 값인 DeliveryType만 OrderDTO가 갖고 있습니다.

2018-08-23 02:16 UTC, 1500sheep commented on src/main/java/com/baemin/nanumchan/web/ApiProductController.java
> +    @PostMapping("/{id}/order")
넵

2018-08-23 02:16 UTC, 1500sheep commented on src/main/java/com/baemin/nanumchan/web/ApiProductController.java
> +    @PostMapping("/{id}/review")
넵

2018-08-23 02:16 UTC, 1500sheep commented on src/main/resources/static/js/ReviewList.js
> +                    return response.json();
바로 적용하겠습니다.(에러 핸들링이 문제였는데 감솨합니다!)

2018-08-23 02:16 UTC, 1500sheep commented on src/main/resources/static/js/detail.js
> +            if(response.status >= 400 && response.status <= 404){
넵!

2018-08-23 02:16 UTC, 1500sheep commented on src/main/resources/static/js/detail.js
> +            if(response.status >= 400 && response.status <= 404){
오...... 네

2018-08-23 02:16 UTC, 1500sheep commented on src/main/resources/static/js/modal.js
> +export function openModal(event){
event 가시죠

2018-08-23 02:16 UTC, 1500sheep commented on src/main/resources/static/js/modal.js
> +    const selectedStars = $('#product1').getElementsByClassName('star');
`('#.star.selected')` 해서 remove 하니깐 완전히 remove가 안되는 경우가 계속 생겨서 `('.star')`로 찾고 `('.selected')` 있을 때 remove하는 경우로 변경했습니다.

2018-08-23 02:16 UTC, 1500sheep commented on src/main/resources/static/js/modal.js
> +    for (let selectedStar of selectedStars) {
넵

2018-08-23 02:45 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/domain/Review.java
> +    public String toString() {
`@ToString(exclude = {"product", "writer})`

2018-08-23 02:46 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/domain/Status.java
> +public enum Status {
enum 자체에도 field를 둬서 구분할 수 있겠네요

2018-08-23 02:47 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/service/ProductService.java
> +    public Order order(Long productId, OrderDTO orderDTO, User user) {
네 controller에서 그렇게 만들어서 넘기는건 별로일까요?

2018-08-23 02:48 UTC, minsungryu commented on src/main/resources/static/js/modal.js
> +export function openModal(event){
그럼 주말에 js쪽 한꺼번에 고칠게요

2018-08-23 05:57 UTC, minsungryu commented on src/main/java/com/baemin/nanumchan/service/ProductService.java
> +        Integer orderCount = (int) (long) orderRepository.countByProduct(product);
orderCount를 꼭 Long으로 받아야할까요?

2018-08-23 06:01 UTC, hyukjin-lee commented on src/main/java/com/baemin/nanumchan/domain/Review.java
> +    public String toString() {
WOW 좀 더 꼼꼼히 찾아봐야겠다...

2018-08-23 06:04 UTC, merged